spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cardb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

